### ISSUE TITLE
Much songs Arent Loading Anymore

### ISSUE THREAD

**Issue by gamingofficeyt** [darknight1050/SongDownloader#2]
Many Songs arent loading anymore (that worked with old BMBF) idk if its the mod or BMBF itself 
But literally Every map you create on Beatsaber dont work anymore. 
And many other of my other maps arent working either i have a logcat and your songloader log just said loaded songs 23...
https://rentry.co/pwhfc <- logcat if its helping 
If you could give me repsonse on Discord would be nice thanks :)
GamingOfficeYT#4405

**Comment by gamingofficeyt** [comment]
EDIT: I maybe found the issue Beatsaber maps with ogg files arent loading with your loader just egg song files can you maybe update your songloader to also accept ogg files.

**Comment by darknight1050** [comment]
Can you upload your songloader log?

**Comment by Dieber** [comment]
> Can you upload your songloader log?

Hello

you could try this song:

https://bsaber.com/songs/b784/

It will show the load error when you select it

**Comment by gamingofficeyt** [comment]
Im at work rn but wabt able to download song cause website is under maintance-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 02.08.21, 19:53 schrieb Florian ***@***.***>:

   
  Can you upload your songloader log?

**Comment by darknight1050** [comment]
> > Can you upload your songloader log?
> 
> Hello
> 
> you could try this song:
> 
> https://bsaber.com/songs/b784/
> 
> It will show the load error when you select it

Yes because this requires the Mapping Extensions mod.

**Comment by gamingofficeyt** [comment]
As i said im not home rn. But The Beatsage maps dont require extensions but also fails at loading just create one with beatsage if you cant wait till im home -- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 03.08.21, 09:16 schrieb Florian ***@***.***>:

   
   
    
    Can you upload your songloader log? 
    
   Hello 
   you could try this song: 
   https://bsaber.com/songs/b784/ 
   It will show the load error when you select it 
   
  Yes because this requires the Mapping Extensions mod.

**Comment by gamingofficeyt** [comment]
[Beat Sage_ Eminem - Crab God 2  - Kanskaart (v2 EE+,S9O,).zip](https://github.com/darknight1050/SongDownloader/files/6924255/Beat.Sage_.Eminem.-.Crab.God.2.-.Kanskaart.v2.EE%2B.S9O.zip)

This Song for example dont require any mods normally this songs also worked fine on old BMBF

**Comment by Number1S0n** [comment]
http://beatsaver.com/maps/491f

Here is another one that crashes BS on launch. I was able to play it on a nightly from 2 weeks ago, but it no longer works for some reason.

**Comment by Number1S0n** [comment]
> [Beat Sage_ Eminem - Crab God 2 - Kanskaart (v2 EE+,S9O,).zip](https://github.com/darknight1050/SongDownloader/files/6924255/Beat.Sage_.Eminem.-.Crab.God.2.-.Kanskaart.v2.EE%2B.S9O.zip)
> 
> This Song for example dont require any mods normally this songs also worked fine on old BMBF

Songs with the extension .ogg will not work sometimes and need to be converted to an .egg

**Comment by darknight1050** [comment]
Beat Sage Errors is a BMBF import bug.
The other one is a SongLoader bug (Obstacles merging for custom levels wasn't disabled) that is now fixed.

**Comment by darknight1050** [comment]
I reported it to the Unicorns hopefully it will get fixed.
