### ISSUE TITLE
SongDownloader keeps crashing the game.

### ISSUE THREAD

**Issue by DeathShot984** [darknight1050/SongDownloader#29]
I don't know when this issue started but, Whenever I try to use SongDownloader to search for songs in game, the moment I click on the button the game crashes. Not sure if another mod is conflicting with this one or if it's this mod that's at fault.
I am currently using the latest version of the mod by the way.

**Comment by FrozenAlex** [comment]
you click on which button? Also we are having a release for 1.37.0 today

**Comment by FrozenAlex** [comment]
Also could you send logs?

**Comment by DeathShot984** [comment]
> Also could you send logs?
Sorry about the late reply, I have been busy with other things.

So the button that I was pressing was the "SONGDOWLOADER" button in the games main menu. I don't know how to send/ get logs for it but as of me writing this, I have just installed the latest version of the mod (as well as 1.37.0) and it seems to be working again. I'm going to try and see if I can replicate the issue again by downgrading back to 1.35.0 and using the old mod version so I'll check back later for another update. :)
